properties([
    parameters ([
        string(name: 'DOCKER_REGISTRY_DOWNLOAD_URL', defaultValue: 'nexus-docker-private-group.ossim.io', description: 'Repository of docker images'),
        string(name: 'BUILD_NODE', defaultValue: 'omar-build', description: 'The build node to run on'),
        string(name: 'OSSIM_BRANCH', defaultValue: 'dev', description: 'The branch to use for ossim'),
        string(name: 'OSSIM_PLUGINS_BRANCH', defaultValue: 'dev', description: 'The branch to use for ossim plugins'),
        string(name: 'OSSIM_OMS_BRANCH', defaultValue: 'dev', description: 'The branch to use for ossim oms'),
        string(name: 'OSSIM_VIDEO_BRANCH', defaultValue: 'dev', description: 'The branch to use for ossim video'),
        string(name: 'OSSIM_DEEPCORE_BRANCH', defaultValue: 'dev', description: 'The branch to use for ossim deepcore'),
        string(name: 'OSSIM_IMAGE_LINKER_BRANCH', defaultValue: 'imageLinker', description: 'The branch to use for ImageLinker'),
        string(name: 'OSSIM_BUILDER_VERSION', defaultValue: '1.0.4', description: 'The version of the ossim builder to be used'),
        booleanParam(name: 'CLEAN_WORKSPACE', defaultValue: true, description: 'Clean the workspace at the end of the run')

    ]),
    pipelineTriggers([
            [$class: "GitHubPushTrigger"]
    ]),
    [$class: 'GithubProjectProperty', displayName: '', projectUrlStr: 'https://github.com/ossimlabs/ossim-ubuntu-minimal.git'],
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '3', daysToKeepStr: '', numToKeepStr: '20')),
    disableConcurrentBuilds()
])
podTemplate(
    containers: [
    containerTemplate(
        name: 'git',
        image: 'alpine/git:latest',
        ttyEnabled: true,
        command: 'cat',
        envVars: [
            envVar(key: 'HOME', value: '/root')
        ]
    ),
    containerTemplate(
      name: 'docker',
      image: 'docker:19.03.8',
      ttyEnabled: true,
      command: 'cat',
      privileged: true
    ),
    containerTemplate(
      image: "${DOCKER_REGISTRY_DOWNLOAD_URL}/ossim-builder-minimal-ubuntu:${OSSIM_BUILDER_VERSION}",
      name: 'builder',
      command: 'cat',
      ttyEnabled: true ,
      alwaysPullImage: true
    )
  ],
  volumes: [
    hostPathVolume(
      hostPath: '/var/run/docker.sock',
      mountPath: '/var/run/docker.sock'
    )
  ]
)
{
timeout(time: 60, unit: 'MINUTES') {
    node(POD_LABEL){

        stage("Checkout")
        {
            scmVars = checkout(scm)


        GIT_BRANCH_NAME = scmVars.GIT_BRANCH
        BRANCH_NAME = """${sh(returnStdout: true, script: "echo ${GIT_BRANCH_NAME} | awk -F'/' '{print \$2}'").trim()}"""
        
    
        preVERSION = readFile "version.txt"
        VERSION = preVERSION.substring(0, preVERSION.indexOf('\n'))

        GIT_TAG_NAME = "ossim-ubuntu" + "-" + VERSION
        ARTIFACT_NAME = "ArtifactName"

        script {
          if (BRANCH_NAME != 'master') {
            buildName "${VERSION} - ${BRANCH_NAME}-SNAPSHOT"
          } else {
            buildName "${VERSION} - ${BRANCH_NAME}"
          }
                
        }
            
        }

        stage("Load Variables")
        {
            withCredentials([string(credentialsId: 'o2-artifact-project', variable: 'o2ArtifactProject')]) {
                step ([$class: "CopyArtifact",
                    projectName: o2ArtifactProject,
                    filter: "common-variables.groovy",
                    flatten: true])
            }

            load "common-variables.groovy"
            
            switch (BRANCH_NAME) {
                case "master":
                  TAG_NAME = VERSION
                  break
        
                case "dev":
                  TAG_NAME = "latest"
                  break
        
                default:
                  TAG_NAME = BRANCH_NAME
                  break
              }
        }

        stage ("Checkout Source Code") 
        {  
            container('git'){  
                dir("builder-image"){
                    dir("ossim-repos/ossim-deepcore"){
                        git(
                            url: 'git@github.com:Maxar-Corp/ossim-deepcore.git',
                            credentialsId: 'ossimlabs-minion-ssh-key',
                            branch: "master"
                        )
                    }
                    sh """
                        apk update && apk add bash
                        ./checkout-ossim.sh
                        cd ossim-repos/ossim-deepcore
                        git checkout ${OSSIM_DEEPCORE_BRANCH}
                    """
                }
            }
        }  

        stage ("Build Ossim")
        {
            container('builder'){
                        sh """
                            mkdir /output
                            mv ./builder-image/ossim-repos/* /work
                            mv ./builder-image/build-scripts/* /build-scripts
                            cd /work
                            /build-scripts/build-ossim.sh
                            mv /output/ ${WORKSPACE}/builder/output/
                        """
                        archiveArtifacts "builder-image/output/ossim-dist-minimal-ubuntu.tgz"
            }
        }
        stage ("Publish to s3 bucket")
                {
                    withAWS(
                        credentials: 'Jenkins IAM User',
                        region: 'us-east-1'){
                            s3Upload(
                                acl: 'PublicRead',
                                bucket: 'o2-delivery',
                                path: "deepcore/ubuntu/ossim-dist-minimal-ubuntu-${env.OSSIM_BUILDER_VERSION}.tgz",
                                file: 'builder-image/output/ossim-dist-minimal-ubuntu.tgz'
                            )
                        }
                }
        stage ("Build Runtime Image")
        {
            container('docker'){
                withDockerRegistry(credentialsId: 'dockerCredentials', url: "https://${DOCKER_REGISTRY_DOWNLOAD_URL}") {
                    dir("runtime") {
                        sh """
                            ./build-docker.sh --network=host
                        """
                    }
                }
            }
        }

        stage ("Publish Docker Image")
        {
            container('docker'){
                withDockerRegistry(credentialsId: 'dockerCredentials', url: "https://${DOCKER_REGISTRY_PRIVATE_UPLOAD_URL}") {
                    sh """
                        docker tag ossim-ubuntu-runtime:local ${DOCKER_REGISTRY_PRIVATE_UPLOAD_URL}/ossim-ubuntu-runtime-18.04:"${VERSION}"
                        docker push ${DOCKER_REGISTRY_PRIVATE_UPLOAD_URL}/ossim-ubuntu-runtime-18.04:"${VERSION}"
                    """
                }
            }
        }

        stage("Clean Workspace")
        {
            if ("${CLEAN_WORKSPACE}" == "true")
                step([$class: 'WsCleanup'])
        }
    }
}
}
//change
