FROM ubuntu:20.04

ENV OSSIM_INSTALL_PREFIX=/usr/local \
    OSSIM_PREFS_FILE=/usr/local/share/ossim/ossim-preferences-template \
    OSSIM_DATA=/data \
    LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib \
    JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 \
    OSSIM_VERSION=1.9.0 \
    OSSIM_VERSION_TAG=SNAPSHOT 

# COPY ./build-kakadu.sh ./build-ossim.sh ./build-joms.sh ./apache-groovy-binary-3.0.13.zip /work/
# COPY ./ossim/ /work/ossim/
# COPY ./ossim-oms/ /work/ossim-oms/
# COPY ./ossim-plugins/ /work/ossim-plugins/
# COPY ./ossim-video/ /work/ossim-video/
# COPY ./ossim-private/ /work/ossim-private/
ADD ./dist/ /usr/local/

RUN echo "" \
    && useradd --uid 1001 --shell /usr/bin/bash omar \
    && chown -R omar:omar /usr/local \
    && apt-get update -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
        bash gdal-bin gdal-data python3-gdal libgdal-java  libgeos++ openjdk-11-jre \
        ffmpeg vim \
    && echo ""

USER omar
WORKDIR /home/omar

CMD bash
